### ISSUE TITLE
it does not add not null expression for nested object which is not IEnumerable

### ISSUE THREAD

**Issue by fyzact** [tghamm/dynamic-linq-query-builder#95]
Hi,
when you have list and in list, if you have nested object which is  null then you get error.

sample field (second searchQueries is array and where is CustomType(object)) if one of "where" field is null then you get null object error.
searchQueries.searchQueries.where.normalization.normalizedName

I have just raised pr https://github.com/tghamm/dynamic-linq-query-builder/pull/94 . welcome feedback.

**Comment by tghamm** [comment]
Hi @fyzact Thanks for the PR.  It looks like it should do the trick.  Is there any chance you'd be willing to add a test case that shows that it solves the issue you described just so it'll be documented for the future?  I have a hard time visualizing the exact scenario from your message, so that would be helpful if you're willing before I merge it.

**Comment by fyzact** [comment]
Hi @tghamm, I have just added test to cover that. Also, I need check object in case null. There is no way to check referacetype as much as I understand. So, would be good also have that.

**Comment by tghamm** [comment]
@fyzact Thanks for adding the test!  I've reviewed the change and accepted the PR.  I'll get a new version out in a little bit.  Appreciate the contribution!
